In [1]:
import numpy as np
import pandas as pd

We'll keep our analysis of G7 countries and looking now at DataFrames. As said, a DataFrame looks a lot like a table (as the one you can appreciate here):

Creating DataFrames manually can be tedious. 99% of the time you'll be pulling the data from a Database, a csv file or the web. But still, you can create a DataFrame by specifying the columns and values:

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

(The columns attribute is optional. I'm using it to keep the same order as in the picture above)

In [3]:
df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

(The columns attribute is optional. I'm using it to keep the same order as in the picture above)

DataFrames also have indexes. As you can see in the "table" above, pandas has assigned a numeric, autoincremental index automatically to each "row" in our DataFrame. In our case, we know that each row represents a country, so we'll just reassign the index:

In [4]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [7]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [8]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [9]:
df.index

Index(['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes

In [11]:
df.size

35

In [12]:
df.shape

(7, 5)

In [13]:
df.describe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [14]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [15]:
df.dtypes.value_counts()

float64    2
int64      2
object     1
Name: count, dtype: int64

Indekslash, tanlash va kesish
Indexing, Selection and Slicing

Individual columns in the DataFrame can be selected with regular indexing. Each column is represented as a Series:

In [16]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [17]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [21]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [22]:
df['population'.title()]

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

Note that the index of the returned Series is the same as the DataFrame one. And its name is the name of the column. If you're working on a notebook and want to see a more DataFrame-like format you can use the to_frame method:

In [23]:
df['Population'].to_frame()

                Population
Canada              35.467
France              63.951
Germany             80.940
Italy               60.665
Japan              127.061
United Kingdom      64.511
United States      318.523

Multiple columns can also be selected similarly to numpy and Series:

In [24]:
df[['Population', 'GDP']]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [26]:
df[1:3]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

Row level selection works better with loc and iloc which are recommended over regular "direct slicing" (df[:]).

In [27]:
df.loc['Italy']

Population       60.665
GDP             2167744
Surface Area     301336
HDI               0.873
Continent        Europe
Name: Italy, dtype: object

In [28]:
df.loc['France': 'Italy']

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [31]:
dt = df.loc['France' : 'Italy', 'Population']

In [33]:
dt = dict(dt)

In [34]:
dt

{'France': 63.951, 'Germany': 80.94, 'Italy': 60.665}

In [35]:
df.loc['France' : 'Italy', ['Population', 'GDP']]

         Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

iloc works with the (numeric) "position" of the index:

In [36]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [37]:
df.iloc[0]

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [38]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [39]:
df.iloc[[0, 1, -1]]

               Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [40]:
df[1:3]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe

In [41]:
df[1:4]

         Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [42]:
df.iloc[1:3, 3]

France     0.888
Germany    0.916
Name: HDI, dtype: float64

In [45]:
df.iloc[1:3, 4]

France     Europe
Germany    Europe
Name: Continent, dtype: object

In [51]:
df.iloc[1 : 3, [1]]

             GDP
France   2833687
Germany  3874437

In [53]:
df.iloc[1 : 3, [0, 1, 2]]

         Population      GDP  Surface Area
France       63.951  2833687        640679
Germany      80.940  3874437        357114

In [54]:
df.iloc[1:3, 1:3]

             GDP  Surface Area
France   2833687        640679
Germany  3874437        357114

In [55]:
df.iloc[1:3, 1:4]

             GDP  Surface Area    HDI
France   2833687        640679  0.888
Germany  3874437        357114  0.916